In [93]:
import numpy as np

In [94]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [95]:
a.shape

(3,)

In [96]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
b[0,2]

3

In [98]:
a=np.zeros((2,2))
a=np.ones((2,2))
a=np.full((2,2),7)
a=np.eye((2))
a=np.random.random((2,2))
a

array([[0.57495544, 0.76152771],
       [0.20660821, 0.23701824]])

In [99]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [100]:
b=a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [101]:
r1=a[1,:]  #in a multy array to select a particular array
r1

array([5, 6, 7, 8])

In [102]:
r2=a[:,1:2]  #in a multy array to select a particular array
r2

array([[ 2],
       [ 6],
       [10]])

In [103]:
r2.shape

(3, 1)

In [104]:
np.array([a[0, 1], a[0, 1]])

array([2, 2])

In [105]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
a[np.arange(4),b]

array([ 1,  6,  7, 11])

In [106]:
a[np.arange(4),b]+=10  #mutation
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [107]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool=(a>2)
bool

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [108]:
a[bool]

array([3, 4, 5, 6])

In [109]:
x = np.array([1, 2])
x.dtype

dtype('int32')

In [110]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [111]:
x = np.array([[1,2],[3,4]])
np.sum(x)
np.sum(x,axis=0)
np.sum(x,axis=1)
x.T

array([[1, 3],
       [2, 4]])

In [112]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=np.empty_like(x)

In [113]:
for i in range(4):
    y[i,:]=x[i,:]+v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [114]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4,1))   # Stack 4 copies of v on top of each other
print(vv)   

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [115]:
y=x+vv
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [116]:
vv = np.tile(v, (4,2))   # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [117]:
vv = np.tile(v, (4,))   # Stack 4 copies of v on top of each other
print(vv)

[1 0 1 1 0 1 1 0 1 1 0 1]


In [118]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasts
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [119]:
y.max()
y.max(axis=1)
np.sqrt(y)
np.sort(y,axis=0)

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [120]:
np.sort(y,axis=0,kind='mergesort')

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

# stacking

In [124]:
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
np.vstack((a, b))
  
# horizontal stacking 
np.hstack((a, b))
  
c = [5, 6] 
  
# stacking columns 
np.column_stack((a, c))

array([[1, 2, 5],
       [3, 4, 6]])

In [125]:
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
np.hsplit(a,2)
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

# time

In [131]:
d=np.datetime64('2019-12-18')

In [132]:
np.datetime64(d,'Y')

numpy.datetime64('2019')

In [134]:
dur=np.datetime64('2019-12-18')-np.datetime64('2010-12-18')
dur

numpy.timedelta64(3287,'D')

In [135]:

# coefficients 
a = np.array([[1, 2], [3, 4]]) 
# constants 
b = np.array([8, 18]) 
  
print("Solution of linear equations:", np.linalg.solve(a, b))

Solution of linear equations: [2. 3.]
